FROM node:22-alpine

WORKDIR /app

ARG SERVICE_NAME
ENV SERVICE_NAME=${SERVICE_NAME}

COPY package*.json ./

COPY apps ./apps

RUN npm ci --omit=dev

ENV NODE_ENV=production

CMD ["sh", "-c", "node apps/${SERVICE_NAME}/src/server.js"]